---
caching:
  expires: 3600
db:
  localhost:
    adapter: postgresql
    encoding: utf8
    host: localhost
    username: sacmac
    password:
    port: 5432
    database: roapi
  ec2:
    adapter: postgresql
    encoding: utf8
    host: localhost
    username: postgres
    password: gefnkfMhFEwwTYAAt3bmcpMj2W84Xp
    port: 5432
    database: roapi
