postgres:
  image: postgres:latest
  volumes:
    - ~/data/fishbase:/var/lib/mysql
  environment:
    - POSTGRES_PASSWORD=root
  restart: always

api:
  build: .
  links:
    - postres

nginx:
  ports:
    - 80:80
  links:
    - api
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  image: nginx
