mysql:
  image: mysql
  ports:
    - "5432"
  volumes:
    - $HOME/data/roapi:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  restart: always

api:
  build: .
  links:
    - mysql

nginx:
  ports:
    - 80:80
  links:
    - api
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  image: nginx
