postgres:
  image: postgres:latest
  volumes:
    - $HOME/data/roapi:/var/lib/postgresql
  environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=root
  restart: always

api:
  build: .
  links:
    - postgres

nginx:
  ports:
    - 80:80
  links:
    - api
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  image: nginx
