geoip:
  image: allingeek/docker-freegeoip

postgres:
  image: postgres:latest
  volumes:
    - ~/data/fishbase:/var/lib/mysql
  environment:
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD

api:
  image: ropensci/roapi:latest
  links:
    - postgres
    - geoip

nginx:
  image: nginx:latest
  ports:
    - "80:80"
  links:
    - api
  volumes:
    - ~/nginx.conf:/etc/nginx/nginx.conf
